// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var LzyImg$ReactHooksTemplate = require("./LzyImg.bs.js");
var Scratch$ReactHooksTemplate = require("./Scratch.bs.js");

console.log(Scratch$ReactHooksTemplate.fibonacciRecur(10));

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  if (match) {
    if (match[0] === "something" && !match[1]) {
      console.log("AT SOMETHING");
    } else {
      console.log("NOT FOUND");
    }
  } else {
    console.log("AT THE ROOT");
  }
  var match$1 = React.useReducer((function (param, action) {
          return /* record */[/* inputValue */action[0]];
        }), /* record */[/* inputValue */""]);
  var dispatch = match$1[1];
  return React.createElement("div", undefined, React.createElement("input", {
                  onChange: (function (_event) {
                      return Curry._1(dispatch, /* Change */[_event.target.value]);
                    })
                }), React.createElement(LzyImg$ReactHooksTemplate.make, {
                  src: "",
                  kind: /* Img */1,
                  alt: ""
                }), React.createElement("button", {
                  onClick: (function (_event) {
                      return ReasonReactRouter.push("/something");
                    })
                }, "Go to something"), React.createElement("button", {
                  onClick: (function (_event) {
                      return ReasonReactRouter.push("/");
                    })
                }, "Go to root"));
}

var make = App;

exports.make = make;
/*  Not a pure module */
