// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function handler(x, param) {
  if (x.length !== 1) {
    console.log("aything else");
    return /* () */0;
  } else {
    var entry = x[0];
    console.log("Just the one tho");
    console.log(entry);
    return /* () */0;
  }
}

function LzyImg(Props) {
  Props.src;
  var kind = Props.kind;
  var alt = Props.alt;
  var rootRef = React.useRef(null);
  React.useEffect((function () {
          var io = new IntersectionObserver(handler);
          Belt_Option.map(Caml_option.nullable_to_opt(rootRef.current), (function (rootRef) {
                  io.observe(rootRef);
                  return /* () */0;
                }));
          return undefined;
        }), /* array */[]);
  if (kind) {
    return React.createElement("img", {
                ref: rootRef,
                alt: alt,
                data: ""
              });
  } else {
    return React.createElement("div", {
                ref: rootRef,
                title: alt
              });
  }
}

var make = LzyImg;

exports.handler = handler;
exports.make = make;
/* react Not a pure module */
